setClass(
   Class="ConstInFlux",
   contains=c("InFlux"),
   slots=list(
    map="numeric"
   )
)
setMethod(
  f="ConstInFlux",
  signature=c(
    map="numeric"
  ),
  definition=function 
  (
    map
    ){
    new("ConstInFlux",map=map)
  }
)
setMethod(
    f="getTimeRange",
    signature="ConstInFlux",
    definition=function 
    ( object){
        return(
               c("t_min"=-Inf,"t_max"=Inf))
    }
)
setMethod(
    f="getFunctionDefinition",
    signature="ConstInFlux",
    definition=function(object){
        return(function(t){object@map})
    }
)
