setMethod(
  f="ConstInFluxes",
  signature=c(
    map="numeric"
  ),
  definition=function 
  (
    map
    ){
    new("ConstInFluxes",map=map)
  }
)
setMethod(
    "ConstInFluxes"
    ,signature=signature(
         map='ConstantInFluxList_by_PoolIndex'
        ,numberOfPools='numeric'
    )
    ,def=function(map,numberOfPools){
        res=rep(0,numberOfPools)
        for (f in map){res[[f@destinationIndex]]<-f@flux_constant}
        ConstInFluxes(map=res)
    }
)
setMethod(
    "getConstantInFluxVector"
    ,signature=signature(
         object='ConstInFluxes'
    )
    ,def=function(object){
        object@map
    }
)
setMethod(
    f="getTimeRange",
    signature="ConstInFluxes",
    definition=function 
    ( object){
        return(
               c("t_min"=-Inf,"t_max"=Inf))
    }
)
setMethod(
    f="getFunctionDefinition",
    signature="ConstInFluxes",
    definition=function(object){
        return(function(t){matrix(ncol=1,object@map)})
    }
)

