setMethod(
  f="GeneralDecompOp",
  signature=signature(object="function"),
  def=function 
  (object){
    UnBoundLinDecompOp(object)
  }
)
setMethod(
  f="InFluxes",
  signature=signature(object="function"),
  def=function 
  (object){
    UnBoundInFluxes(object)
  }
)
