setMethod(
  f="GeneralDecompOp",
  signature=signature(object="function"),
  def=function 
  (object){
    UnBoundLinDecompOp(object)
  }
)
setMethod(
  f="InFlux",
  signature=signature(object="function"),
  def=function 
  (object){
    UnBoundInFlux(object)
  }
)
