setMethod(
  f="InFlux",
  signature=signature(object="list"),
  def=function 
  (object){
    BoundInFlux(TimeMap(object))
  }
)
setMethod(
  f="GeneralDecompOp",
  signature=signature(object="list"),
  def=function 
  (object){
    BoundLinDecompOp(TimeMap(object))
  }
)
