setClass(
   Class="PoolTarget",
   slots=c(destinationId='PoolId')
)
setMethod(
  f="PoolTarget",
  signature=c(destination='numeric'),
  def=function(destination){
    new('PoolTarget',destinationId=PoolId(destination))
  }
)
