setClass(
    Class="UnBoundInFlux",
    contains=c("InFlux"),
    slots=list( map="function")
)
setMethod(
     f="initialize",
     signature="UnBoundInFlux",
     definition=function 
     (.Object,map=function(){})
     {
        .Object@map=map
     return(.Object)
     }
)
setMethod(
      f="UnBoundInFlux",
      signature=c(map="function"),
      definition=function 
      (map){
      return(new("UnBoundInFlux",map=map))
     }
)
setMethod(
    f="getFunctionDefinition",
    signature="UnBoundInFlux",
    definition=function 
    (object){
      return(object@map)
    }
)
setMethod(
    f="getTimeRange",
    signature="UnBoundInFlux",
    definition=function 
    (object)
    {
        return( c("t_min"=-Inf,"t_max"=Inf))
    }
)
