---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# SoilR

<!-- badges: start -->
<!-- badges: end -->

The goal of SoilR is to ...

## Installation

You can install the released version of SoilR from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("SoilR")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("MPIBGC-TEE/SoilR-exp")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
requireNamespace('pkgload')
pkgload::load_all('.')
# define initial values for the state variables
times<-seq(from=1,to=100,by=0.1)
smod <- Wang3psym()
plotPoolGraph(smod)
state_variable_names(smod)
iv=c(barrel=1,glass=5)
modrun=Model_by_PoolNames( smod=smod ,times=times ,initialValues=iv)
#   
sol <- getSolution(modrun)
##plotPoolGraph(modrun)
## shortcut overview plot
plot(modrun)
```
